/* Carte d'aventure enfant - commercial-v2 */
(function(){
  const THEMES={
    pirates:{name:'Pirates',icon:'🏴‍☠️',hero:'⛵',goal:'🏝️',stages:['⚓','🦜','🌴','🗿','🐚','🦀','💰','🏝️']},
    space:{name:'Espace',icon:'🚀',hero:'🚀',goal:'🪐',stages:['🌍','🌙','🛰️','☄️','⭐','👽','🌌','🪐']},
    dinos:{name:'Dinosaures',icon:'🦖',hero:'🦕',goal:'🌋',stages:['🥚','🌿','🦴','🦖','🌴','🐾','🔥','🌋']},
    magic:{name:'Forêt enchantée',icon:'🧚',hero:'🦄',goal:'🏰',stages:['🍄','🌸','🐇','🧚','🌈','🔮','🐉','🏰']},
    ocean:{name:'Océan',icon:'🐠',hero:'🐬',goal:'🐋',stages:['🐚','🐠','🪸','🐢','🦀','🧜','⭐','🐋']},
    safari:{name:'Safari',icon:'🦁',hero:'🚙',goal:'🦁',stages:['🌾','🦒','🐘','🦓','🐒','🦏','🌅','🦁']}
  };
  const POINTS=[[9,70],[22,48],[35,68],[48,39],[61,60],[73,34],[84,54],[93,25]];
  function ensure(c){c.adventure??={enabled:true,showButton:true,theme:'pirates',goal:120,period:'week',showStars:true,showPercent:true};c.adventure.enabled??=true;c.adventure.showButton??=true;c.adventure.theme??='pirates';c.adventure.goal??=120;c.adventure.period??='week';c.adventure.showStars??=true;c.adventure.showPercent??=true;c.childTools??={};c.childTools.adventure??=true}
  app.profiles.forEach(p=>ensure(p.cfg||(p.cfg={})));bind();ensure(cfg);save();
  function mondayLocal(d=new Date()){const x=new Date(d),q=x.getDay()||7;x.setHours(12,0,0,0);x.setDate(x.getDate()-q+1);return x}
  function addLocal(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}
  function earned(){if(cfg.adventure.period==='all')return allDays().reduce((n,[,d])=>n+score(d.state||{}),0);const m=mondayLocal(),start=key(m),end=key(addLocal(m,6));return allDays().filter(([k])=>k>=start&&k<=end).reduce((n,[,d])=>n+score(d.state||{}),0)}
  function progress(){const stars=earned(),goal=Math.max(10,Number(cfg.adventure.goal)||120);return{stars,goal,pct:Math.min(100,Math.round(stars/goal*100))}}
  function heroPoint(pct){const pos=(Math.max(0,Math.min(100,pct))/100)*(POINTS.length-1),i=Math.min(POINTS.length-2,Math.floor(pos)),f=pos-i,a=POINTS[i],b=POINTS[i+1];return{x:a[0]+(b[0]-a[0])*f,y:a[1]+(b[1]-a[1])*f}}
  function svgPath(){return 'M 9 70 C 14 60,18 49,22 48 S 31 67,35 68 S 43 42,48 39 S 57 58,61 60 S 69 37,73 34 S 80 51,84 54 S 90 31,93 25'}
  function mapHtml(){ensure(cfg);const th=THEMES[cfg.adventure.theme]||THEMES.pirates,p=progress(),step=Math.min(7,Math.floor(p.pct/12.5)),hp=heroPoint(p.pct);return `<div class="adventureScene theme-${cfg.adventure.theme}"><div class="adventureTitle">${th.icon} ${th.name}</div><div class="adventureRoute"><svg class="adventurePath" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><path class="adventurePathShadow" d="${svgPath()}"/><path class="adventurePathLine" d="${svgPath()}"/></svg>${th.stages.map((s,i)=>{const [x,y]=POINTS[i];return `<button class="adventureNode ${i<=step?'reached':''} ${i===step?'current':''}" style="left:${x}%;top:${y}%" onclick="adventureNodeInfo(${i})"><span>${s}</span><small>${i===7?'ARRIVÉE':`Étape ${i+1}`}</small></button>`}).join('')}<div class="adventureHero" style="left:${hp.x}%;top:${hp.y}%">${th.hero}</div></div><div class="adventureGoal">${p.pct>=100?`🎉 Aventure terminée ! ${th.goal}`:`Encore <b>${Math.max(0,p.goal-p.stars)} ⭐</b> pour atteindre ${th.goal}`}</div>${cfg.adventure.showPercent?`<div class="adventureProgress"><i style="width:${p.pct}%"></i></div><strong class="adventurePct">${p.pct}%</strong>`:''}${cfg.adventure.showStars?`<div class="adventureStars">⭐ ${p.stars} / ${p.goal}</div>`:''}<small class="adventurePeriod">${cfg.adventure.period==='week'?'Progression de cette semaine':'Progression depuis le début'}</small></div>`}
  window.adventureNodeInfo=function(i){const th=THEMES[cfg.adventure.theme]||THEMES.pirates,p=progress(),needed=Math.ceil((i+1)/8*p.goal),ok=p.stars>=needed;const msg=ok?`Étape ${i+1} atteinte ! 🎉`:`Il faut environ ${Math.max(0,needed-p.stars)} ⭐ de plus pour cette étape.`;const n=document.createElement('div');n.className='adventureToast';n.textContent=`${th.stages[i]} ${msg}`;document.body.appendChild(n);setTimeout(()=>n.remove(),1800)};
  window.openChildAdventure=function(){if(!cfg.kidMode||!cfg.adventure.enabled)return;document.getElementById('childToolOverlay')?.remove();const o=document.createElement('div');o.id='childToolOverlay';o.className='overlay open childToolOverlay';o.innerHTML=`<div class="kidToolModal adventureModal"><div class="kidToolHead"><div class="kidToolTitle"><span>🗺️</span><h2>Mon aventure</h2></div><button class="kidToolClose" onclick="closeChildTool()">✕</button></div>${mapHtml()}<button class="btn kidToolBack" onclick="closeChildTool()">← Retour à ma journée</button></div>`;document.body.appendChild(o)};
  function settingsHtml(){ensure(cfg);return `<div class="settingsGroup adventureSettings"><h3>🗺️ Carte d'aventure</h3><label class="toggleRow"><span>Activer la carte d'aventure</span><input type="checkbox" ${cfg.adventure.enabled?'checked':''} onchange="cfg.adventure.enabled=this.checked;save();render()"></label><label class="toggleRow"><span>Afficher dans l'espace enfant</span><input type="checkbox" ${cfg.adventure.showButton?'checked':''} onchange="cfg.adventure.showButton=this.checked;cfg.childTools.adventure=this.checked;save();render()"></label><div class="settingInline"><span>Univers</span><select onchange="cfg.adventure.theme=this.value;save();render()">${Object.entries(THEMES).map(([k,t])=>`<option value="${k}" ${cfg.adventure.theme===k?'selected':''}>${t.icon} ${t.name}</option>`).join('')}</select></div><div class="settingInline"><span>Période</span><select onchange="cfg.adventure.period=this.value;save();render()"><option value="week" ${cfg.adventure.period==='week'?'selected':''}>Cette semaine</option><option value="all" ${cfg.adventure.period==='all'?'selected':''}>Depuis le début</option></select></div><div class="settingInline"><span>Objectif</span><select onchange="cfg.adventure.goal=Number(this.value);save();render()">${[40,60,80,100,120,150,180,200,250,300,400,500].map(n=>`<option value="${n}" ${Number(cfg.adventure.goal)===n?'selected':''}>${n} ⭐</option>`).join('')}</select></div><label class="toggleRow"><span>Afficher les étoiles</span><input type="checkbox" ${cfg.adventure.showStars?'checked':''} onchange="cfg.adventure.showStars=this.checked;save();render()"></label><label class="toggleRow"><span>Afficher le pourcentage</span><input type="checkbox" ${cfg.adventure.showPercent?'checked':''} onchange="cfg.adventure.showPercent=this.checked;save();render()"></label><button class="btn" onclick="previewAdventure()">👀 Aperçu</button></div>`}
  window.previewAdventure=function(){const was=cfg.kidMode;cfg.kidMode=true;openChildAdventure();cfg.kidMode=was};
  function injectSettings(){const host=document.getElementById('settingsView')?.querySelector('.box');if(!host)return;host.querySelectorAll('.adventureSettings').forEach(x=>x.remove());const holder=document.createElement('div');holder.innerHTML=settingsHtml();const node=holder.firstElementChild;node.classList.add('settingsCollapsed');const h=node.querySelector('h3');h.classList.add('settingsAccordionTitle');h.insertAdjacentHTML('beforeend','<span class="settingsChevron">⌄</span>');h.addEventListener('click',()=>node.classList.toggle('settingsCollapsed'));host.appendChild(node)}
  function updateButton(){const b=document.getElementById('childAdventureBtn');if(b)b.style.display=cfg.kidMode&&cfg.adventure.enabled&&cfg.adventure.showButton?'flex':'none'}
  const prevSettings=window.renderSettings;window.renderSettings=function(){prevSettings();ensure(cfg);injectSettings()};const prevRender=window.render;window.render=function(){prevRender();ensure(cfg);updateButton()};if(typeof renderSettings==='function')renderSettings();updateButton();
})();