function monday(d){const x=new Date(d),q=x.getDay()||7;x.setHours(12,0,0,0);x.setDate(x.getDate()-q+1);return x}
function add(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}
let weekOffset=0,statsRange=7;
function changeWeek(n){weekOffset=Math.min(0,weekOffset+n);renderWeek()}
function currentWeek(){weekOffset=0;renderWeek()}
function renderWeek(){const m=add(monday(new Date()),weekOffset*7),names=['Lun','Mar','Mer','Jeu','Ven','Sam','Dim'];let total=0,potTotal=0,closed=0,h='';for(let i=0;i<7;i++){const d=add(m,i),r=db.days[key(d)],p=r?percent(score(r.state||{}),maxScore()):0;if(r){total+=score(r.state||{});potTotal+=(r.pot?.pee||0)+(r.pot?.poop||0);if(r.closed)closed++}h+=`<div class="day ${key(d)===key()?'today':''}"><b>${names[i]}</b><div>${d.getDate()}/${d.getMonth()+1}</div><strong>${key(d)>key()?'—':p+'%'}</strong><div>${r?.closed?'🏁':key(d)>key()?'⏳':r?'📝':'—'}</div></div>`}weekRange.textContent=`Du ${m.toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'})} au ${add(m,6).toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'})}`;weekInfo.innerHTML=`⭐ <b>${total}</b> étoiles · 🚽 <b>${potTotal}</b> réussites pot · 🏁 <b>${closed}</b> journée(s) clôturée(s)`;weekGrid.innerHTML=h;nextWeekBtn.disabled=weekOffset>=0}
function rangeRecords(days){const entries=allDays();if(!days)return entries;const start=key(add(new Date(),-(days-1)));return entries.filter(([k])=>k>=start&&k<=key())}
function setStatsRange(n){statsRange=n;renderStats()}
function renderStats(){const recs=rangeRecords(statsRange);let stars=0,pot=0,closed=0,great=0,ratings=0;for(const[,d]of recs){stars+=score(d.state||{});pot+=(d.pot?.pee||0)+(d.pot?.poop||0);if(d.closed)closed++;Object.values(d.state||{}).forEach(v=>{ratings++;if(v===2)great++})}const avg=closed?Math.round(recs.filter(([,d])=>d.closed).reduce((a,[,d])=>a+percent(score(d.state||{}),maxScore()),0)/closed):0;statsInfo.innerHTML=`<p><b>Période :</b> ${statsRange?statsRange+' derniers jours':'tout l’historique'}</p><p>⭐ Total étoiles : <b>${stars}</b></p><p>🏁 Journées clôturées : <b>${closed}</b></p><p>📈 Moyenne des journées clôturées : <b>${avg}%</b></p><p>🌟 Évaluations « très bien » : <b>${ratings?Math.round(great/ratings*100):0}%</b></p><p>🔥 Meilleure série historique : <b>${streak()}</b></p><p>🚽 Réussites pot : <b>${pot}</b></p>`;renderBadges()}
function avatarHtml(){return cfg.photo?`<img src="${cfg.photo}" alt="">`:cfg.avatar}
function profileStars(p){const oc=cfg,od=db;cfg=p.cfg;db=p.db;const n=totals().stars;cfg=oc;db=od;return n}
function profileAvatarHtml(p){return p.cfg.photo?`<img src="${p.cfg.photo}" alt="">`:(p.cfg.avatar||'🦁')}
function renderProfiles(){topAvatar.innerHTML=avatarHtml();topName.textContent=cfg.childName;profileSelector.innerHTML=app.profiles.map(p=>`<button class="chip ${p.id===app.activeId?'active':''}" onclick="switchProfile('${p.id}')"><div class="profileChipAvatar">${profileAvatarHtml(p)}</div><b>${p.cfg.childName||'Champion'}</b><div>⭐ ${profileStars(p)}</div></button>`).join('');childNameInput.value=cfg.childName;avatarChoices.innerHTML=avatars.map(a=>`<button class="avatarChoiceBtn ${!cfg.photo&&cfg.avatar===a?'active':''}" onclick="chooseAvatar('${a}')">${a}</button>`).join('')}
function addProfile(){const name=prompt('Prénom du nouvel enfant ?','Champion');if(!name)return;const p=newProfile(name,avatars[app.profiles.length%avatars.length]);app.profiles.push(p);app.activeId=p.id;bind();save();weekOffset=0;render();showView('settings')}
function switchProfile(id){app.activeId=id;bind();save();weekOffset=0;render()}
function deleteProfile(){if(app.profiles.length===1)return alert('Il faut garder au moins un profil.');if(!confirm('Supprimer ce profil et tout son historique ?'))return;app.profiles=app.profiles.filter(p=>p.id!==app.activeId);app.activeId=app.profiles[0].id;bind();save();weekOffset=0;render()}
function setChildName(v){cfg.childName=v||'Champion';save();renderProfiles()}
function chooseAvatar(a){cfg.avatar=a;cfg.photo='';save();renderProfiles()}
function handlePhoto(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=c.height=256;const ctx=c.getContext('2d'),z=Math.max(256/img.width,256/img.height),w=img.width*z,h=img.height*z;ctx.drawImage(img,(256-w)/2,(256-h)/2,w,h);cfg.photo=c.toDataURL('image/jpeg',.7);save();renderProfiles()};img.src=r.result};r.readAsDataURL(f)}
function removePhoto(){cfg.photo='';save();renderProfiles()}
function renderSettings(){kidToggle.checked=cfg.kidMode;rewardInput.value=cfg.reward||'';peeMode.textContent=`Pipi : ${cfg.pottyMode.pee==='counter'?'🔢 Compteur':'⭐ Étoiles'}`;poopMode.textContent=`Caca : ${cfg.pottyMode.poop==='counter'?'🔢 Compteur':'⭐ Étoiles'}`;blockSettings.innerHTML=ORDER.map(k=>`<div class="toggleRow"><label><input type="checkbox" ${cfg.blocks[k]?'checked':''} onchange="cfg.blocks['${k}']=this.checked;save();render()"> ${GROUPS[k].title}</label></div>`).join('');taskSettings.innerHTML=ORDER.map(k=>`<h4>${GROUPS[k].title}</h4>`+GROUPS[k].tasks.map(t=>`<label style="display:block;padding:5px"><input type="checkbox" ${cfg.tasks[t[0]]!==false?'checked':''} onchange="cfg.tasks['${t[0]}']=this.checked;save();render()"> ${t[1]} ${t[2]}</label>`).join('')).join('')}
function togglePotMode(k){cfg.pottyMode[k]=cfg.pottyMode[k]==='counter'?'stars':'counter';save();render()}
function setKidMode(v){cfg.kidMode=v;save();render();showView('today')}
function changePin(){const v=newPin.value.replace(/\D/g,'');if(v.length!==4)return alert('Le code doit contenir 4 chiffres.');cfg.parentPin=v;save();newPin.value='';alert('Code modifié')}
let entered='';
function openPin(){entered='';pinError.textContent='';pinOverlay.classList.add('open');drawPin()}
function closePin(){pinOverlay.classList.remove('open')}
function drawPin(){pinDots.textContent='● '.repeat(entered.length)+'○ '.repeat(4-entered.length);keypad.innerHTML=[1,2,3,4,5,6,7,8,9,'⌫',0,'✓'].map(k=>`<button class="key" onclick="pinKey('${k}')">${k}</button>`).join('')}
function pinKey(k){if(k==='⌫')entered=entered.slice(0,-1);else if(k==='✓'){if(entered===cfg.parentPin){closePin();cfg.kidMode=false;save();render();showView('today')}else{entered='';pinError.textContent='Code incorrect'}}else if(entered.length<4)entered+=k;drawPin()}
function showView(v){for(const x of ['today','week','stats','settings']){document.getElementById(x+'View').classList.toggle('active',x===v);document.getElementById(x+'Tab').classList.toggle('active',x===v)}if(v==='week')renderWeek();if(v==='stats')renderStats()}
function goToday(){const badgeOverlay=document.getElementById('kidBadgesOverlay');if(badgeOverlay)badgeOverlay.remove();showView('today');window.scrollTo({top:0,behavior:'smooth'})}
function enterChildMode(){cfg.kidMode=true;save();render();showView('today');window.scrollTo({top:0,behavior:'smooth'})}
function requestParentMode(){if(!cfg.kidMode){showView('settings');window.scrollTo({top:0,behavior:'smooth'});return}openPin()}
function exportData(){const payload={format:'journeeChampionBackup',version:2,exportedAt:new Date().toISOString(),app};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`champion-sauvegarde-${key()}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function importData(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);const incoming=data?.format==='journeeChampionBackup'?data.app:data;if(!incoming?.profiles?.length)throw new Error();if(!confirm('Importer cette sauvegarde remplacera les données actuellement présentes sur cet appareil. Continuer ?'))return;app=incoming;app.profiles.forEach(p=>{if(typeof migrateBreakfastData==='function')migrateBreakfastData(p)});bind();save();weekOffset=0;render();alert('Sauvegarde importée ✓')}catch(err){alert('Fichier de sauvegarde invalide.')}finally{e.target.value=''}};r.readAsText(f)}
function actionButtons(id){return `<div class="actionChoices"><button class="actionChoice good" onclick="mark('${id}',2,event)">🌟</button><button class="actionChoice midbtn" onclick="mark('${id}',1,event)">😊</button><button class="actionChoice cloudbtn" onclick="mark('${id}',0,event)">☁️</button></div>`}
function uniformTaskCard(t){const v=db.days[key()].state[t[0]];return `<div class="actionCard ${cls(v)}"><div class="actionHead"><span class="actionEmoji">${t[1]}</span><span class="actionName">${t[2]}</span></div>${actionButtons(t[0])}</div>`}
function uniformPottyCard(t){const k=t[0]==='pot-pee'?'pee':'poop';if(cfg.pottyMode[k]==='stars')return uniformTaskCard(t);const n=db.days[key()].pot[k]||0;return `<div class="actionCard"><div class="actionHead"><span class="actionEmoji">🚽</span><span class="actionName">${t[2]}</span></div><div class="actionCount">${n}</div><div class="actionCounter"><button class="minus" onclick="pot('${k}',-1)">−</button><button class="plus" onclick="pot('${k}',1)">＋</button></div></div>`}
function groupLayoutClass(count){return count<=4?'oneRow':'twoRows'}
function renderToday(){const day=db.days[key()];if(day.closed){todayBlocks.innerHTML=`<div class="box closed"><div style="font-size:58px">🏁🏆</div><h2>Journée clôturée</h2><p>⭐ ${score(day.state)} étoiles</p><button class="btn" onclick="reopenDay()">🔓 Rouvrir</button></div>`;finishBtn.style.display='none';return}finishBtn.style.display='block';let html='';for(const gk of ORDER){const g=GROUPS[gk];if(!cfg.blocks[gk])continue;const tasks=g.tasks.filter(t=>cfg.tasks[t[0]]!==false);if(!tasks.length)continue;const cards=tasks.map(t=>g.type==='potty'?uniformPottyCard(t):uniformTaskCard(t)).join('');html+=`<section class="box"><h2 class="sectionTitle">${g.title}</h2><div class="actionViewport"><div class="actionGrid ${groupLayoutClass(tasks.length)}">${cards}</div></div></section>`}todayBlocks.innerHTML=html}
function closedRecords(){return Object.values(db.days).filter(d=>d.closed)}
function countGreat(id){return closedRecords().filter(d=>d.state?.[id]===2).length}
function countAtLeast(p){return closedRecords().filter(d=>percent(score(d.state||{}),maxScore())>=p).length}
function countPerfect(){const a=activeIds();return a.length?closedRecords().filter(d=>a.every(id=>d.state?.[id]===2)).length:0}
function countAllAtLeastOne(){const a=activeIds();return a.length?closedRecords().filter(d=>a.every(id=>(d.state?.[id]??-1)>=1)).length:0}
function groupPerfectCount(groupKey){const ids=GROUPS[groupKey].tasks.filter(t=>cfg.tasks[t[0]]!==false).map(t=>t[0]);return ids.length?closedRecords().filter(d=>ids.every(id=>d.state?.[id]===2)).length:0}
BADGES.push(['days3','🗓️','3 aventures','bronze',()=>totals().closed>=3],['day70','😊','Belle journée','bronze',()=>countAtLeast(70)>=1],['morning1','🌞','Matin de champion','bronze',()=>groupPerfectCount('morning')>=1],['evening1','🌙','Soirée de champion','bronze',()=>groupPerfectCount('evening')>=1],['polite3','🙏','Super poli','bronze',()=>countGreat('please')>=3&&countGreat('thanks')>=3],['helper3','🤝','Petit assistant','bronze',()=>countGreat('help')>=3],['tidy3','🧸','As du rangement','bronze',()=>countGreat('tidy')>=3],['listen3','👂','Oreilles de lynx','bronze',()=>countGreat('listen')>=3],['calm3','🧘','Je retrouve mon calme','bronze',()=>countGreat('calm')>=3],['table3','🍽️','Champion à table','bronze',()=>countGreat('table')>=3],['quiet3','😴','Roi du temps calme','bronze',()=>countGreat('quiet-time')>=3],['days7','📆','Une semaine d’aventures','silver',()=>totals().closed>=7],['morning5','🌅','5 matins au top','silver',()=>groupPerfectCount('morning')>=5],['evening5','🌜','5 soirées au top','silver',()=>groupPerfectCount('evening')>=5],['polite10','💖','Politesse en or','silver',()=>countGreat('please')>=10&&countGreat('thanks')>=10],['helper10','🦸','Super assistant','silver',()=>countGreat('help')>=10],['tidy10','🧹','Maître du rangement','silver',()=>countGreat('tidy')>=10],['listen10','🦊','Super écoute','silver',()=>countGreat('listen')>=10],['calm10','🌿','Maître du calme','silver',()=>countGreat('calm')>=10],['pot25','🚽','As du pot','silver',()=>totals().pot>=25],['stars500','🚀','500 étoiles','gold',()=>totals().stars>=500],['days14','🌟','Deux semaines d’efforts','gold',()=>totals().closed>=14],['perfect1','👑','Journée parfaite','gold',()=>countPerfect()>=1],['perfect3','🏆','Triple perfection','gold',()=>countPerfect()>=3],['balanced5','🌈','Toujours je progresse','gold',()=>countAllAtLeastOne()>=5],['pot50','🏅','Propreté champion','gold',()=>totals().pot>=50],['school5','🎓','Petit écolier','gold',()=>countGreat('focus')>=5||countGreat('homework')>=5||countGreat('reading')>=5],['autonomy5','🧭','Je deviens autonome','gold',()=>countGreat('shoes')>=5||countGreat('coat')>=5||countGreat('laundry')>=5],['days30plus','🗓️','Un mois de champion','legendary',()=>totals().closed>=30],['stars1000','🌌','1000 étoiles','legendary',()=>totals().stars>=1000],['pot100','💫','100 réussites au pot','legendary',()=>totals().pot>=100],['perfect10','👑','Légende des journées parfaites','legendary',()=>countPerfect()>=10],['days50','🏰','50 aventures terminées','legendary',()=>totals().closed>=50],['days100','🐉','100 jours de champion','legendary',()=>totals().closed>=100]);
function openKidBadges(){updateBadges();const unlocked=BADGES.filter(b=>cfg.badgesUnlocked[b[0]]).length;const o=document.createElement('div');o.className='overlay open';o.id='kidBadgesOverlay';o.innerHTML=`<div class="kidBadgeModal"><div style="font-size:52px">🏅✨</div><h2>Mes badges</h2><div class="kidBadgeScore">${unlocked} / ${BADGES.length} débloqués</div><div class="kidBadgeGrid">${BADGES.map(b=>{const ok=!!cfg.badgesUnlocked[b[0]];return `<div class="kidBadgeCard ${ok?b[3]:'locked'}"><div class="kidBadgeIcon">${ok?b[1]:'🔒'}</div><div class="kidBadgeName">${b[2]}</div><small>${ok?b[3].toUpperCase():'À débloquer'}</small></div>`}).join('')}</div><button class="btn closeKidBadges" onclick="document.getElementById('kidBadgesOverlay').remove();goToday()">← Retour à ma journée</button></div>`;document.body.appendChild(o)}
function render(){bind();document.body.classList.toggle('kid',cfg.kidMode);renderProfiles();renderToday();renderWeek();renderStats();renderSettings();const d=db.days[key()],n=score(d.state||{}),m=maxScore();summary.innerHTML=`<div class="pill">⭐ ${n} / ${m}</div>${d.closed?'<div class="pill">🏁 Journée clôturée</div>':''}`;childModeBtn.setAttribute('aria-pressed',cfg.kidMode?'true':'false');parentModeBtn.setAttribute('aria-pressed',cfg.kidMode?'false':'true')}
render();