function monday(d){const x=new Date(d),q=x.getDay()||7;x.setHours(12,0,0,0);x.setDate(x.getDate()-q+1);return x}
function add(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}
function renderWeek(){const m=monday(new Date()),names=['Lun','Mar','Mer','Jeu','Ven','Sam','Dim'];let total=0,potTotal=0,h='';for(let i=0;i<7;i++){const d=add(m,i),r=db.days[key(d)],p=r?percent(score(r.state||{}),maxScore()):0;if(r){total+=score(r.state||{});potTotal+=(r.pot?.pee||0)+(r.pot?.poop||0)}h+=`<div class="day ${key(d)===key()?'today':''}"><b>${names[i]}</b><div>${d.getDate()}/${d.getMonth()+1}</div><strong>${key(d)>key()?'—':p+'%'}</strong><div>${r?.closed?'🏁':key(d)>key()?'⏳':p>=80?'🌟':p>=55?'😊':'☁️'}</div></div>`}weekInfo.innerHTML=`⭐ Cette semaine : <b>${total}</b> · 🚽 pot : <b>${potTotal}</b>`;weekGrid.innerHTML=h}
function renderStats(){const t=totals();statsInfo.innerHTML=`<p>⭐ Total étoiles : <b>${t.stars}</b></p><p>🏁 Journées clôturées : <b>${t.closed}</b></p><p>🔥 Meilleure série : <b>${streak()}</b></p><p>🚽 Réussites pot : <b>${t.pot}</b></p>`;renderBadges()}
function avatarHtml(){return cfg.photo?`<img src="${cfg.photo}" alt="">`:cfg.avatar}
function profileStars(p){const oc=cfg,od=db;cfg=p.cfg;db=p.db;const n=totals().stars;cfg=oc;db=od;return n}
function renderProfiles(){topAvatar.innerHTML=avatarHtml();topName.textContent=cfg.childName;profileSelector.innerHTML=app.profiles.map(p=>`<button class="chip ${p.id===app.activeId?'active':''}" onclick="switchProfile('${p.id}')"><div>${p.cfg.photo?'📷':p.cfg.avatar||'🦁'}</div><b>${p.cfg.childName||'Champion'}</b><div>⭐ ${profileStars(p)}</div></button>`).join('');childNameInput.value=cfg.childName;avatarChoices.innerHTML=avatars.map(a=>`<button class="btn" onclick="chooseAvatar('${a}')">${a}</button>`).join('')}
function addProfile(){const name=prompt('Prénom du nouvel enfant ?','Champion');if(!name)return;const p=newProfile(name,avatars[app.profiles.length%avatars.length]);app.profiles.push(p);app.activeId=p.id;bind();save();render();showView('settings')}
function switchProfile(id){app.activeId=id;bind();save();render()}
function deleteProfile(){if(app.profiles.length===1)return alert('Il faut garder au moins un profil.');if(!confirm('Supprimer ce profil et tout son historique ?'))return;app.profiles=app.profiles.filter(p=>p.id!==app.activeId);app.activeId=app.profiles[0].id;bind();save();render()}
function setChildName(v){cfg.childName=v||'Champion';save();renderProfiles()}
function chooseAvatar(a){cfg.avatar=a;cfg.photo='';save();renderProfiles()}
function handlePhoto(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=c.height=256;const ctx=c.getContext('2d'),z=Math.max(256/img.width,256/img.height),w=img.width*z,h=img.height*z;ctx.drawImage(img,(256-w)/2,(256-h)/2,w,h);cfg.photo=c.toDataURL('image/jpeg',.7);save();renderProfiles()};img.src=r.result};r.readAsDataURL(f)}
function removePhoto(){cfg.photo='';save();renderProfiles()}
function renderSettings(){kidToggle.checked=cfg.kidMode;rewardInput.value=cfg.reward||'';peeMode.textContent=`Pipi : ${cfg.pottyMode.pee==='counter'?'🔢 Compteur':'⭐ Étoiles'}`;poopMode.textContent=`Caca : ${cfg.pottyMode.poop==='counter'?'🔢 Compteur':'⭐ Étoiles'}`;blockSettings.innerHTML=ORDER.map(k=>`<div class="toggleRow"><label><input type="checkbox" ${cfg.blocks[k]?'checked':''} onchange="cfg.blocks['${k}']=this.checked;save();render()"> ${GROUPS[k].title}</label></div>`).join('');taskSettings.innerHTML=ORDER.map(k=>`<h4>${GROUPS[k].title}</h4>`+GROUPS[k].tasks.map(t=>`<label style="display:block;padding:5px"><input type="checkbox" ${cfg.tasks[t[0]]!==false?'checked':''} onchange="cfg.tasks['${t[0]}']=this.checked;save();render()"> ${t[1]} ${t[2]}</label>`).join('')).join('')}
function togglePotMode(k){cfg.pottyMode[k]=cfg.pottyMode[k]==='counter'?'stars':'counter';save();render()}
function setKidMode(v){cfg.kidMode=v;save();render();showView('today')}
function changePin(){const v=newPin.value.replace(/\D/g,'');if(v.length!==4)return alert('Le code doit contenir 4 chiffres.');cfg.parentPin=v;save();newPin.value='';alert('Code modifié')}
let entered='';
function openPin(){entered='';pinError.textContent='';pinOverlay.classList.add('open');drawPin()}
function closePin(){pinOverlay.classList.remove('open')}
function drawPin(){pinDots.textContent='● '.repeat(entered.length)+'○ '.repeat(4-entered.length);keypad.innerHTML=[1,2,3,4,5,6,7,8,9,'⌫',0,'✓'].map(k=>`<button class="key" onclick="pinKey('${k}')">${k}</button>`).join('')}
function pinKey(k){if(k==='⌫')entered=entered.slice(0,-1);else if(k==='✓'){if(entered===cfg.parentPin){closePin();document.body.classList.remove('kid');showView('settings')}else{entered='';pinError.textContent='Code incorrect'}}else if(entered.length<4)entered+=k;drawPin()}
function showView(v){for(const x of ['today','week','stats','settings']){document.getElementById(x+'View').classList.toggle('active',x===v);document.getElementById(x+'Tab').classList.toggle('active',x===v)}}
function render(){bind();document.body.classList.toggle('kid',cfg.kidMode);renderProfiles();renderToday();renderWeek();renderStats();renderSettings();const d=db.days[key()],n=score(d.state||{}),m=maxScore();summary.innerHTML=`<div class="pill">⭐ ${n} / ${m}</div>${d.closed?'<div class="pill">🏁 Journée clôturée</div>':''}`}
render();