const GROUPS={
 morning:{title:'☀️ Matin',type:'routine',tasks:[['dress','👕','Je m’habille'],['teeth','🪥','Je me brosse les dents'],['breakfast-eat','🥣','Je mange mon petit-déjeuner'],['breakfast-clear','🧺','Je range mon petit-déjeuner']]},
 evening:{title:'🌙 Soir',type:'routine',tasks:[['evening-wash','🛁','Je me lave'],['evening-pajamas','🥱','Je mets mon pyjama'],['evening-teeth','🪥','Je me brosse les dents'],['bedtime','🛏️','Je respecte le coucher']]},
 cleanliness:{title:'🚽 Propreté',type:'potty',tasks:[['pot-pee','🚽','Pipi sur le pot'],['pot-poop','🚽','Caca sur le pot']]},
 behaviors:{title:'💛 Comportements',type:'behavior',tasks:[['please','🙏','Je dis s’il te plaît'],['thanks','❤️','Je dis merci'],['talk','🗣️','Je parle gentiment'],['help','🤝','J’aide'],['tidy','🧸','Je range'],['listen','👂','J’écoute'],['calm','🌬️','Je retrouve mon calme'],['table','🍽️','Je reste à table']]},
 rest:{title:'😴 Temps calme',type:'behavior',tasks:[['quiet-time','😴','Je respecte le temps calme']]},
 school:{title:'🎒 École',type:'behavior',tasks:[['homework','📚','Je fais mes activités'],['focus','🧠','Je reste concentré'],['reading','📖','Je regarde un livre']]},
 autonomy:{title:'🏠 Autonomie',type:'routine',tasks:[['shoes','👟','Je mets mes chaussures'],['coat','🧥','Je range mon manteau'],['laundry','🧺','Je range mon linge sale']]}
};
const ORDER=['morning','evening','cleanliness','behaviors','rest','school','autonomy'];
const avatars=['🦁','🦊','🐼','🦄','🚀','🛡️','⭐','🐯','🐸','🐻'];
const APPKEY='journeeChampionMultiV2',OLDAPP='journeeChampionMultiV1',OLDDB='journeeChampionHistoryV2',OLDCF='journeeChampionConfigV1';
const baseCfg={kidMode:false,parentPin:'0000',reward:'Ma récompense surprise 🎁',childName:'Champion',avatar:'🦁',photo:'',badgesUnlocked:{},pottyMode:{pee:'counter',poop:'counter'},blocks:{morning:true,evening:true,cleanliness:true,behaviors:true,rest:true,school:false,autonomy:false},tasks:{}};
Object.values(GROUPS).forEach(g=>g.tasks.forEach(t=>baseCfg.tasks[t[0]]=!['homework','focus','reading','shoes','coat','laundry'].includes(t[0])));
const clone=x=>JSON.parse(JSON.stringify(x));
const key=(d=new Date())=>d.toLocaleDateString('en-CA');
function newProfile(name='Champion',avatar='🦁'){return{id:'p'+Date.now()+Math.random().toString(36).slice(2,7),cfg:{...clone(baseCfg),childName:name,avatar},db:{days:{}}}}
function migrateBreakfastData(p){const c=p?.cfg,d=p?.db;if(!c||!d?.days)return;if(c.tasks?.breakfast!==undefined){if(c.tasks['breakfast-eat']===undefined)c.tasks['breakfast-eat']=c.tasks.breakfast;if(c.tasks['breakfast-clear']===undefined)c.tasks['breakfast-clear']=c.tasks.breakfast;delete c.tasks.breakfast}for(const day of Object.values(d.days)){if(day?.state&&day.state.breakfast!==undefined){if(day.state['breakfast-eat']===undefined)day.state['breakfast-eat']=day.state.breakfast;delete day.state.breakfast}}}
function loadApp(){let a=null;try{a=JSON.parse(localStorage.getItem(APPKEY))}catch(e){}if(a?.profiles?.length){a.profiles.forEach(migrateBreakfastData);return a}try{a=JSON.parse(localStorage.getItem(OLDAPP))}catch(e){}if(a?.profiles?.length){a.profiles.forEach(migrateBreakfastData);localStorage.setItem(APPKEY,JSON.stringify(a));return a}let p=newProfile();try{const c=JSON.parse(localStorage.getItem(OLDCF));if(c)p.cfg={...p.cfg,...c,blocks:{...p.cfg.blocks,...c.blocks},tasks:{...p.cfg.tasks,...c.tasks},pottyMode:{...p.cfg.pottyMode,...c.pottyMode},badgesUnlocked:{...p.cfg.badgesUnlocked,...c.badgesUnlocked}}}catch(e){}try{const d=JSON.parse(localStorage.getItem(OLDDB));if(d?.days)p.db=d}catch(e){}migrateBreakfastData(p);return{activeId:p.id,profiles:[p]}}
let app=loadApp(),profile,cfg,db;
function bind(){profile=app.profiles.find(p=>p.id===app.activeId)||app.profiles[0];app.activeId=profile.id;profile.cfg=profile.cfg||clone(baseCfg);profile.db=profile.db||{days:{}};migrateBreakfastData(profile);cfg=profile.cfg;db=profile.db;cfg.blocks={...baseCfg.blocks,...cfg.blocks};cfg.tasks={...baseCfg.tasks,...cfg.tasks};cfg.pottyMode={...baseCfg.pottyMode,...cfg.pottyMode};cfg.badgesUnlocked=cfg.badgesUnlocked||{};cfg.parentPin=cfg.parentPin||'0000';cfg.childName=cfg.childName||'Champion';cfg.avatar=cfg.avatar||'🦁';db.days=db.days||{};db.days[key()]=db.days[key()]||{state:{},pot:{pee:0,poop:0},closed:false};db.days[key()].state=db.days[key()].state||{};db.days[key()].pot=db.days[key()].pot||{pee:0,poop:0}}
function save(){localStorage.setItem(APPKEY,JSON.stringify(app))}
bind();save();
function activeIds(){const out=[];for(const gk of ORDER){const g=GROUPS[gk];if(!cfg.blocks[gk])continue;for(const t of g.tasks){if(cfg.tasks[t[0]]===false)continue;if(g.type==='potty'){const k=t[0]==='pot-pee'?'pee':'poop';if(cfg.pottyMode[k]!=='stars')continue}out.push(t[0])}}return out}
function score(state={}){return activeIds().reduce((n,id)=>n+(state[id]??0),0)}
function maxScore(){return activeIds().length*2}
function percent(n,m){return m?Math.round(n/m*100):0}
function cls(v){return v===2?'great':v===1?'mid':v===0?'cloud':''}
function buttons(id,small=false){const c=small?'miniChoice':'choice';return `<div class="${small?'miniChoices':'choices'}"><button class="${c} good" onclick="mark('${id}',2,event)">🌟</button><button class="${c} midbtn" onclick="mark('${id}',1,event)">😊</button><button class="${c} cloudbtn" onclick="mark('${id}',0,event)">☁️</button></div>`}
function morningCard(t){const v=db.days[key()].state[t[0]];return `<div class="miniTask ${cls(v)}"><div class="miniHead"><span class="miniEmoji">${t[1]}</span><span class="miniName">${t[2]}</span></div>${buttons(t[0],true)}</div>`}
function taskCard(t){const v=db.days[key()].state[t[0]];return `<div class="task ${cls(v)}"><div class="emoji">${t[1]}</div><div class="taskName">${t[2]}</div>${buttons(t[0])}</div>`}
function pottyCard(t){const k=t[0]==='pot-pee'?'pee':'poop';if(cfg.pottyMode[k]==='stars')return taskCard(t);const n=db.days[key()].pot[k]||0;return `<div class="potCard"><div class="emoji">🚽</div><div class="taskName">${t[2]}</div><div class="potCount">${n}</div><div class="counter"><button class="minus" onclick="pot('${k}',-1)">−</button><button class="plus" onclick="pot('${k}',1)">＋</button></div></div>`}
function renderToday(){const day=db.days[key()];if(day.closed){todayBlocks.innerHTML=`<div class="box closed"><div style="font-size:58px">🏁🏆</div><h2>Journée clôturée</h2><p>⭐ ${score(day.state)} étoiles</p><button class="btn" onclick="reopenDay()">🔓 Rouvrir</button></div>`;finishBtn.style.display='none';return}finishBtn.style.display='block';let html='';for(const gk of ORDER){const g=GROUPS[gk];if(!cfg.blocks[gk])continue;const tasks=g.tasks.filter(t=>cfg.tasks[t[0]]!==false);if(!tasks.length)continue;if(gk==='morning'){html+=`<section class="box"><h2 class="sectionTitle">${g.title}</h2><div class="morningStrip">${tasks.map(morningCard).join('')}</div></section>`}else if(g.type==='potty'){html+=`<section class="box"><h2 class="sectionTitle">${g.title}</h2><div class="potGrid">${tasks.map(pottyCard).join('')}</div></section>`}else{html+=`<section class="box"><h2 class="sectionTitle">${g.title}</h2><div class="grid">${tasks.map(taskCard).join('')}</div></section>`}}todayBlocks.innerHTML=html}
function fx(e,v){if(!e)return;const chars=v===2?['⭐','✨','🎉']:v===1?['😊','✨']:['☁️','💨'];chars.forEach((ch,i)=>{const s=document.createElement('span');s.textContent=ch;s.style.cssText=`position:fixed;z-index:3000;pointer-events:none;font-size:30px;left:${e.clientX+(i-1)*22}px;top:${e.clientY}px;transition:.7s`;document.body.appendChild(s);requestAnimationFrame(()=>{s.style.transform=`translateY(-90px) rotate(${i*25}deg)`;s.style.opacity='0'});setTimeout(()=>s.remove(),800)})}
function mark(id,v,e){if(db.days[key()].closed)return;const s=db.days[key()].state;if(s[id]===v)delete s[id];else{s[id]=v;fx(e,v)}save();render()}
function pot(k,d){if(db.days[key()].closed)return;db.days[key()].pot[k]=Math.max(0,(db.days[key()].pot[k]||0)+d);save();render()}
function finishDay(){const d=db.days[key()];if(d.closed)return;const missing=activeIds().filter(id=>d.state[id]===undefined).length;if(!confirm(missing?`Il reste ${missing} mission(s) non renseignée(s). Clôturer quand même ?`:'Clôturer la journée ?'))return;d.closed=true;d.closedAt=new Date().toISOString();save();const b=updateBadges();render();if(b)showBadge(b)}
function reopenDay(){if(confirm('Rouvrir la journée ?')){db.days[key()].closed=false;save();render()}}
function allDays(){return Object.entries(db.days).sort((a,b)=>a[0].localeCompare(b[0]))}
function totals(){let stars=0,pot=0,closed=0;for(const[,d]of allDays()){stars+=score(d.state||{});pot+=(d.pot?.pee||0)+(d.pot?.poop||0);if(d.closed)closed++}return{stars,pot,closed}}
function streak(){let c=0,b=0;for(const[,d]of allDays()){if(d.closed&&percent(score(d.state||{}),maxScore())>=55){c++;b=Math.max(b,c)}else if(d.closed)c=0}return b}
const BADGES=[['first','🎈','Première aventure','bronze',()=>totals().closed>=1],['stars25','⭐','25 étoiles','bronze',()=>totals().stars>=25],['pot5','🚽','5 réussites au pot','bronze',()=>totals().pot>=5],['day90','🏆','Journée en or','silver',()=>Object.values(db.days).some(d=>d.closed&&percent(score(d.state||{}),maxScore())>=90)],['stars50','🌠','50 étoiles','silver',()=>totals().stars>=50],['streak3','🔥','3 jours de suite','silver',()=>streak()>=3],['stars100','💯','100 étoiles','gold',()=>totals().stars>=100],['streak5','🔥','5 jours de suite','gold',()=>streak()>=5],['stars250','💎','250 étoiles','legendary',()=>totals().stars>=250],['streak7','🌈','7 jours de suite','legendary',()=>streak()>=7],['days30','🦸','30 journées clôturées','legendary',()=>totals().closed>=30]];
function updateBadges(){for(const b of BADGES){if(!cfg.badgesUnlocked[b[0]]&&b[4]()){cfg.badgesUnlocked[b[0]]=new Date().toISOString();save();return b}}return null}
function showBadge(b){const o=document.createElement('div');o.className='overlay open';o.innerHTML=`<div class="modal"><div style="font-size:85px">${b[1]}</div><h2>✨ NOUVEAU BADGE ✨</h2><h1>${b[2]}</h1><p>${b[3].toUpperCase()}</p><button class="btn" onclick="this.closest('.overlay').remove()">Trop bien ! 🎉</button></div>`;document.body.appendChild(o)}
function renderBadges(){badgeSummary.textContent=`${BADGES.filter(b=>cfg.badgesUnlocked[b[0]]).length}/${BADGES.length} débloqués`;badgeGrid.innerHTML=BADGES.map(b=>`<div class="badge ${cfg.badgesUnlocked[b[0]]?b[3]:'locked'}"><div class="badgeIcon">${cfg.badgesUnlocked[b[0]]?b[1]:'🔒'}</div><b>${b[2]}</b><div>${b[3]}</div></div>`).join('')}
