/* Edition/rattrapage parental d'une journée depuis l'historique. */
(function(){
  let editingDayKey=null,createdForEdit=false;
  function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function editChoices(id,v){return `<div class="historyEditChoices"><button class="actionChoice good ${v===2?'selected':''}" onclick="setHistoryRating('${id}',2)">🌟</button><button class="actionChoice midbtn ${v===1?'selected':''}" onclick="setHistoryRating('${id}',1)">😊</button><button class="actionChoice cloudbtn ${v===0?'selected':''}" onclick="setHistoryRating('${id}',0)">☁️</button><button class="btn historyClearRating" onclick="clearHistoryRating('${id}')">—</button></div>`}
  function dateFromDayKey(k){const [y,m,d]=k.split('-').map(Number);return new Date(y,m-1,d,12)}
  function renderEditor(){const day=db.days[editingDayKey];if(!day)return;const date=dateFromDayKey(editingDayKey);let groups='';for(const gk of ORDER){const g=GROUPS[gk];if(!g||!cfg.blocks[gk])continue;const tasks=g.tasks.filter(t=>cfg.tasks[t[0]]!==false);if(!tasks.length)continue;const rows=tasks.map(t=>{if(g.type==='potty'){const pk=t[0]==='pot-pee'?'pee':'poop';if(cfg.pottyMode[pk]==='counter')return `<div class="historyMission historyEditMission"><div><span class="historyEmoji">${t[1]}</span><b>${t[2]}</b></div><div class="historyPotEdit"><button class="minus" onclick="changeHistoryPot('${pk}',-1)">−</button><strong>${day.pot?.[pk]||0}</strong><button class="plus" onclick="changeHistoryPot('${pk}',1)">＋</button></div></div>`}return `<div class="historyMission historyEditMission"><div><span class="historyEmoji">${t[1]}</span><b>${t[2]}</b></div>${editChoices(t[0],day.state?.[t[0]])}</div>`}).join('');groups+=`<section class="historyGroup"><h3>${g.title}</h3>${rows}</section>`}let o=document.getElementById('historyDetailOverlay');if(!o){o=document.createElement('div');o.id='historyDetailOverlay';o.className='overlay open';document.body.appendChild(o)}o.innerHTML=`<div class="historyDetailModal historyEditModal"><div class="historyDetailHead"><div><h2>✏️ ${date.toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</h2><div class="historySummary">${createdForEdit?'Rattrapage de la journée':'Modification parentale'}</div></div><button class="historyClose" onclick="cancelHistoryEdit()">✕</button></div>${groups}<section class="historyGroup"><h3>📝 Note parentale</h3><textarea id="historyEditNote" class="field historyNoteField" rows="4" placeholder="Fatigue, sortie, journée particulière…">${esc(day.note||'')}</textarea></section><div class="historyEditFooter"><button class="btn" onclick="cancelHistoryEdit()">Annuler</button><button class="finish" onclick="saveHistoryEdit()">💾 Enregistrer et clôturer</button></div></div>`}
  window.startHistoryEdit=function(dayKey){if(cfg.kidMode||dayKey>key())return;let day=db.days[dayKey];createdForEdit=!day;if(!day){day=db.days[dayKey]={state:{},pot:{pee:0,poop:0},closed:false};}editingDayKey=dayKey;day._editBackup=createdForEdit?null:JSON.stringify({state:day.state||{},pot:day.pot||{},note:day.note||'',closed:day.closed,rewardSnapshot:day.rewardSnapshot||null});day.closed=false;renderEditor()};
  window.setHistoryRating=function(id,v){if(!editingDayKey)return;db.days[editingDayKey].state=db.days[editingDayKey].state||{};db.days[editingDayKey].state[id]=v;renderEditor()};
  window.clearHistoryRating=function(id){if(!editingDayKey)return;delete db.days[editingDayKey].state?.[id];renderEditor()};
  window.changeHistoryPot=function(k,n){if(!editingDayKey)return;const d=db.days[editingDayKey];d.pot=d.pot||{pee:0,poop:0};d.pot[k]=Math.max(0,(d.pot[k]||0)+n);renderEditor()};
  window.cancelHistoryEdit=function(){if(!editingDayKey)return closeDayDetail();const dk=editingDayKey,d=db.days[dk];if(createdForEdit)delete db.days[dk];else if(d?._editBackup){const b=JSON.parse(d._editBackup);d.state=b.state;d.pot=b.pot;d.note=b.note;d.closed=b.closed;if(b.rewardSnapshot)d.rewardSnapshot=b.rewardSnapshot;else delete d.rewardSnapshot;delete d._editBackup}editingDayKey=null;createdForEdit=false;closeDayDetail();renderWeek();renderStats()};
  window.saveHistoryEdit=function(){if(!editingDayKey)return;const d=db.days[editingDayKey];d.note=document.getElementById('historyEditNote')?.value.trim()||'';d.closed=true;delete d.rewardSnapshot;delete d._editBackup;d.editedAt=new Date().toISOString();save();editingDayKey=null;createdForEdit=false;closeDayDetail();render();showView('week')};
  const oldOpen=window.openDayDetail;window.openDayDetail=function(dayKey){oldOpen(dayKey);const d=db.days[dayKey],modal=document.querySelector('#historyDetailOverlay .historyDetailModal');if(!d||!modal||cfg.kidMode)return;const close=modal.querySelector('.historyBottomClose');if(close)close.insertAdjacentHTML('beforebegin',`<button class="btn historyEditBtn" onclick="startHistoryEdit('${dayKey}')">✏️ Modifier cette journée</button>`)};
  const oldRenderWeek=window.renderWeek;window.renderWeek=function(){oldRenderWeek();if(cfg.kidMode)return;const m=add(monday(new Date()),weekOffset*7);document.querySelectorAll('#weekGrid .day').forEach((el,i)=>{const dk=key(add(m,i));if(dk>=key()||db.days[dk])return;el.classList.add('clickable','catchupDay');el.disabled=false;el.innerHTML=el.innerHTML.replace(/<small>.*?<\/small>/,'')+'<small>＋ Rattraper</small>';el.onclick=()=>startHistoryEdit(dk)})};
  if(typeof renderWeek==='function')renderWeek();
})();