/* Timer général indépendant. N'utilise pas l'ancien timer par mission. */
(function(){
  let audioCtx=null;
  function unlockAudio(){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;audioCtx=audioCtx||new C();if(audioCtx.state==='suspended')audioCtx.resume()}catch(e){}}
  function chime(){try{unlockAudio();if(!audioCtx)return;const t=audioCtx.currentTime;[[523.25,0],[659.25,.16],[783.99,.32],[1046.5,.55]].forEach(([f,d])=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(.0001,t+d);g.gain.exponentialRampToValueAtTime(.14,t+d+.02);g.gain.exponentialRampToValueAtTime(.0001,t+d+.25);o.connect(g);g.connect(audioCtx.destination);o.start(t+d);o.stop(t+d+.27)})}catch(e){}}
  function state(){return cfg.routineTimer||null}
  function remaining(){const s=state();return s?Math.max(0,Math.ceil((s.endAt-Date.now())/1000)):0}
  function fmt(sec){const m=Math.floor(sec/60),s=sec%60;return String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')}
  function removeModal(){document.getElementById('routineTimerOverlay')?.remove()}
  function button(){return document.getElementById('routineTimerBtn')}
  function ensureButtonParts(){const b=button();if(!b)return null;if(!b.querySelector('.timerBtnIcon'))b.innerHTML='<span class="timerBtnIcon" aria-hidden="true">⏱️</span><span class="timerBtnText">Timer</span>';return b}
  function renderButton(){const b=ensureButtonParts();if(!b)return;const s=state(),r=remaining(),text=b.querySelector('.timerBtnText');b.classList.toggle('running',!!s&&r>0);b.classList.toggle('finished',!!s&&r===0);if(text)text.textContent=!s?'Timer':r>0?fmt(r):'Terminé'}
  function confetti(){for(let i=0;i<18;i++){const e=document.createElement('span');e.className='timerConfetti';e.textContent=['⭐','✨','🎉'][i%3];e.style.left=(20+Math.random()*60)+'vw';e.style.top=(35+Math.random()*20)+'vh';e.style.setProperty('--tx',(Math.random()*260-130)+'px');document.body.appendChild(e);setTimeout(()=>e.remove(),1300)}}
  function finish(){const s=state();if(!s||s.notified)return;s.notified=true;s.finished=true;save();chime();if(navigator.vibrate)navigator.vibrate([160,70,160,70,220]);const msg=document.getElementById('routineTimerMessage');if(msg)msg.innerHTML='🎉 <b>Le temps est terminé !</b>';const card=document.getElementById('routineTimerCard');if(card)card.classList.add('timerDone');confetti()}
  function tick(){renderButton();const s=state();if(!s)return;const r=remaining(),clock=document.getElementById('routineTimerClock'),bar=document.getElementById('routineTimerBar');if(clock)clock.textContent=fmt(r);if(bar){const p=s.duration?Math.max(0,Math.min(100,r/s.duration*100)):0;bar.style.width=p+'%'}if(r===0)finish()}
  window.openRoutineTimer=function(){unlockAudio();const s=state();if(s){openRunning();return}removeModal();const o=document.createElement('div');o.id='routineTimerOverlay';o.className='overlay open';o.innerHTML=`<div class="timerModal generalTimerModal"><div class="generalTimerIcon">⏱️</div><h2>Mon timer</h2><p>Combien de temps ?</p><div class="timerPresets generalPresets">${[2,5,10,15,20,30].map(n=>`<button class="timerPreset" onclick="startRoutineTimer(${n})">${n}<small> min</small></button>`).join('')}</div><button class="btn timerCancelBtn" onclick="closeRoutineTimer()">Annuler</button></div>`;document.body.appendChild(o)};
  window.startRoutineTimer=function(min){unlockAudio();cfg.routineTimer={duration:min*60,endAt:Date.now()+min*60000,notified:false,finished:false};save();openRunning();tick()};
  function openRunning(){removeModal();const o=document.createElement('div');o.id='routineTimerOverlay';o.className='overlay open';o.innerHTML=`<div class="timerModal generalTimerModal" id="routineTimerCard"><div class="generalTimerIcon">⏱️</div><div class="timerClock" id="routineTimerClock">00:00</div><div class="timerProgress"><div class="timerProgressBar" id="routineTimerBar"></div></div><div class="generalTimerMessage" id="routineTimerMessage">${remaining()?'Tu as le temps, avance tranquillement 🌟':'🎉 <b>Le temps est terminé !</b>'}</div><div class="timerControls"><button class="btn" onclick="closeRoutineTimer()">Masquer</button><button class="btn" onclick="addRoutineTimerMinute()">+1 min</button><button class="btn" onclick="stopRoutineTimer()">⏹ Arrêter</button></div></div>`;document.body.appendChild(o);tick()}
  window.closeRoutineTimer=function(){removeModal()};
  window.addRoutineTimerMinute=function(){const s=state();if(!s)return;s.endAt=Math.max(Date.now(),s.endAt)+60000;s.duration=(s.duration||0)+60;s.notified=false;s.finished=false;save();tick()};
  window.stopRoutineTimer=function(){if(!state())return;if(!confirm('Arrêter le timer ?'))return;cfg.routineTimer=null;save();removeModal();tick()};
  window.addEventListener('load',()=>{ensureButtonParts();renderButton();setInterval(tick,500)});
})();