/* Commercial V2 : boutique virtuelle de récompenses. */
(function(){
const DEFAULT=[['🎬','Choisir le film',80],['📚','Une histoire en plus',40],['🎲','Choisir un jeu en famille',70],['🍰','Choisir le dessert',60],['🌳','Sortie au parc',120]];
function ensure(c){c.starShop??={enabled:false,showChildButton:true,spendStars:false,items:DEFAULT.map((x,i)=>({id:'default-'+i,emoji:x[0],label:x[1],price:x[2],enabled:true})),requests:[]};c.starShop.showChildButton??=true}
app.profiles.forEach(p=>ensure(p.cfg||(p.cfg={})));bind();ensure(cfg);save();
function earned(){return totals().stars}
function spent(){return cfg.starShop.requests.filter(r=>r.status==='approved'&&r.deducted).reduce((n,r)=>n+r.price,0)}
function balance(){return Math.max(0,earned()-spent())}
function itemCards(child=false){const items=cfg.starShop.items.filter(i=>i.enabled!==false);if(!items.length)return '<p>Aucune récompense disponible.</p>';return `<div class="shopGrid">${items.map(i=>`<div class="shopCard"><div class="shopEmoji">${i.emoji}</div><b>${i.label}</b><strong>${i.price} ⭐</strong>${child?`<button class="btn primaryBtn" ${balance()<i.price?'disabled':''} onclick="requestShopReward('${i.id}')">${balance()<i.price?'Pas assez ⭐':'Je la veux !'}</button>`:''}</div>`).join('')}</div>`}
window.openStarShop=function(forcePreview=false){if(!cfg.starShop.enabled&&!forcePreview)return alert('La boutique est désactivée. Active-la dans les paramètres parents.');const o=document.createElement('div');o.className='overlay open';o.innerHTML=`<div class="modal childToolModal shopModal"><button class="historyClose" onclick="this.closest('.overlay').remove()">✕</button><div class="shopModalHead"><div><h2>🛍️ Ma boutique</h2><p>Choisis une récompense et demande-la à tes parents.</p></div><div class="shopBalance">⭐ ${balance()}</div></div>${itemCards(true)}<p class="muted">Une demande doit être validée par un parent.</p></div>`;document.body.appendChild(o)};
window.previewStarShop=function(){openStarShop(true)};
window.requestShopReward=function(id){const i=cfg.starShop.items.find(x=>x.id===id);if(!i||balance()<i.price)return;cfg.starShop.requests.push({id:'req-'+Date.now(),itemId:i.id,label:i.label,emoji:i.emoji,price:i.price,status:'pending',createdAt:new Date().toISOString(),deducted:false});save();document.querySelector('.shopModal')?.closest('.overlay')?.remove();alert('🎉 Demande envoyée aux parents !')};
window.reviewShopRequest=function(id,status){const r=cfg.starShop.requests.find(x=>x.id===id);if(!r||r.status!=='pending')return;if(status==='approved'&&cfg.starShop.spendStars&&balance()<r.price)return alert('Solde insuffisant.');r.status=status;r.reviewedAt=new Date().toISOString();r.deducted=status==='approved'&&cfg.starShop.spendStars;save();render();showView('settings')};
window.addShopItem=function(){const label=document.getElementById('shopLabel')?.value.trim(),emoji=document.getElementById('shopEmoji')?.value.trim()||'🎁',price=Math.max(1,Number(document.getElementById('shopPrice')?.value)||1);if(!label)return alert('Donne un nom à la récompense.');cfg.starShop.items.push({id:'shop-'+Date.now().toString(36),label,emoji,price,enabled:true});save();render();showView('settings')};
window.deleteShopItem=function(id){cfg.starShop.items=cfg.starShop.items.filter(i=>i.id!==id);save();render();showView('settings')};
function requests(){const rs=[...cfg.starShop.requests].reverse().slice(0,20);return rs.length?rs.map(r=>`<div class="shopRequest"><span>${r.emoji} <b>${r.label}</b> · ${r.price} ⭐</span><span>${r.status==='pending'?`<button class="btn" onclick="reviewShopRequest('${r.id}','approved')">✅ Valider</button> <button class="btn" onclick="reviewShopRequest('${r.id}','rejected')">❌ Refuser</button>`:r.status==='approved'?'✅ Validée':'❌ Refusée'}</span></div>`).join(''):'<div class="emptyState">📭 Aucune demande pour le moment.</div>'}
function editor(){return `<div class="shopTable">${cfg.starShop.items.map(i=>`<div class="shopEditRow"><span class="shopEditEmoji">${i.emoji}</span><div class="shopEditName"><b>${i.label}</b><small>${i.price} ⭐</small></div><label class="shopVisible"><input type="checkbox" ${i.enabled!==false?'checked':''} onchange="cfg.starShop.items.find(x=>x.id==='${i.id}').enabled=this.checked;save()"> Visible</label><button class="btn dangerBtn" onclick="deleteShopItem('${i.id}')">Supprimer</button></div>`).join('')}</div>`}
function settings(){return `<div class="settingsGroup starShopSettings"><h3>🛍️ Boutique de récompenses</h3><div class="shopStatus ${cfg.starShop.enabled?'on':'off'}"><div><b>${cfg.starShop.enabled?'Boutique active':'Boutique désactivée'}</b><small>${cfg.starShop.enabled?'Le bouton peut apparaître en mode enfant.':'Active-la pour permettre à l’enfant d’y accéder.'}</small></div><button class="btn" onclick="previewStarShop()">👀 Aperçu enfant</button></div><div class="shopOptionGrid"><label class="shopOptionCard"><span>🛍️ Activer la boutique</span><input type="checkbox" ${cfg.starShop.enabled?'checked':''} onchange="cfg.starShop.enabled=this.checked;save();render()"></label><label class="shopOptionCard"><span>👶 Afficher « Ma boutique »</span><input type="checkbox" ${cfg.starShop.showChildButton?'checked':''} onchange="cfg.starShop.showChildButton=this.checked;save();render()"></label><label class="shopOptionCard"><span>⭐ Dépenser les étoiles</span><input type="checkbox" ${cfg.starShop.spendStars?'checked':''} onchange="cfg.starShop.spendStars=this.checked;save()"></label></div><div class="shopParentBalance"><div>Capital gagné<br><b>${earned()} ⭐</b></div><div>Solde boutique<br><b>${balance()} ⭐</b></div></div><h4>Récompenses</h4><div class="shopCreate"><input id="shopEmoji" class="field" maxlength="4" value="🎁"><input id="shopLabel" class="field" placeholder="Ex. Choisir le dîner"><input id="shopPrice" class="field" type="number" min="1" value="80"><button class="btn primaryBtn" onclick="addShopItem()">＋ Ajouter</button></div>${editor()}<h4>Demandes de l’enfant</h4>${requests()}</div>`}
function inject(){const box=document.querySelector('#settingsView > .box');if(!box)return;box.querySelector('.starShopSettings')?.remove();const h=document.createElement('div');h.innerHTML=settings();const n=h.firstElementChild;n.classList.add('settingsCollapsed');const title=n.querySelector('h3');title.classList.add('settingsAccordionTitle');title.insertAdjacentHTML('beforeend','<span class="settingsChevron">⌄</span>');title.onclick=()=>n.classList.toggle('settingsCollapsed');box.appendChild(n)}
function childButton(){let b=document.getElementById('childShopBtn');if(!b){b=document.createElement('button');b.id='childShopBtn';b.className='childToolBtn shop';b.innerHTML='🛍️ Ma boutique';b.onclick=()=>openStarShop(false);document.getElementById('childSideTools')?.appendChild(b)}b.style.display=cfg.kidMode&&cfg.starShop.enabled&&cfg.starShop.showChildButton?'flex':'none'}
const prevSettings=window.renderSettings;window.renderSettings=function(){prevSettings();ensure(cfg);inject()};const prevRender=window.render;window.render=function(){prevRender();ensure(cfg);childButton()};inject();childButton();
})();