/* Commercial V2 : coffres / surprises enfant. */
(function(){
const DEFAULT_CONTENT=[
 {id:'bonus10',emoji:'✨',label:'Bonus de 10 étoiles symboliques',type:'bonus'},
 {id:'story',emoji:'📚',label:'Une histoire bonus',type:'reward'},
 {id:'movie',emoji:'🎬',label:'Choisir le film',type:'reward'},
 {id:'game',emoji:'🎲',label:'Choisir un jeu en famille',type:'reward'},
 {id:'mystery',emoji:'🎁',label:'Surprise choisie par les parents',type:'reward'}
];
function ensure(c){
 c.chests??={enabled:false,showChildButton:true,triggers:{weekly:true,stars:false,badge:false,challenge:false},starsGoal:100,content:DEFAULT_CONTENT.map(x=>({...x,enabled:true})),history:[],openedKeys:{}};
 c.chests.triggers??={weekly:true,stars:false,badge:false,challenge:false};c.chests.content??=DEFAULT_CONTENT.map(x=>({...x,enabled:true}));c.chests.history??=[];c.chests.openedKeys??={};
}
app.profiles.forEach(p=>ensure(p.cfg||(p.cfg={})));bind();ensure(cfg);save();
function weekKey(){const d=new Date(),q=d.getDay()||7,x=new Date(d);x.setHours(12,0,0,0);x.setDate(x.getDate()-q+1);return key(x)}
function weekStars(){const m=weekKey(),d=new Date(m+'T12:00:00'),end=key(new Date(d.getFullYear(),d.getMonth(),d.getDate()+6,12));return allDays().filter(([k])=>k>=m&&k<=end).reduce((n,[,x])=>n+score(x.state||{}),0)}
function weekClosed(){const m=weekKey(),d=new Date(m+'T12:00:00'),end=key(new Date(d.getFullYear(),d.getMonth(),d.getDate()+6,12));return allDays().filter(([k,x])=>k>=m&&k<=end&&x.closed).length}
function challengeDone(){const ch=cfg.weeklyChallenge||{};if(!ch.taskId)return false;const target=Number(ch.target)||5,m=weekKey(),d=new Date(m+'T12:00:00'),end=key(new Date(d.getFullYear(),d.getMonth(),d.getDate()+6,12));const count=allDays().filter(([k,x])=>k>=m&&k<=end&&x.state?.[ch.taskId]===2).length;return count>=target}
function latestBadgeStamp(){return Object.values(cfg.badgesUnlocked||{}).filter(Boolean).sort().pop()||''}
function eligible(){ensure(cfg);const list=[];
 if(cfg.chests.triggers.weekly&&weekClosed()>=5)list.push({key:'weekly-'+weekKey(),reason:'🏆 Belle semaine',label:'Coffre de la semaine'});
 if(cfg.chests.triggers.stars&&weekStars()>=Number(cfg.chests.starsGoal||100))list.push({key:'stars-'+weekKey()+'-'+cfg.chests.starsGoal,reason:'⭐ Objectif étoiles atteint',label:'Coffre des étoiles'});
 if(cfg.chests.triggers.challenge&&challengeDone())list.push({key:'challenge-'+weekKey(),reason:'🎯 Défi réussi',label:'Coffre du défi'});
 const badge=latestBadgeStamp();if(cfg.chests.triggers.badge&&badge)list.push({key:'badge-'+badge,reason:'🏅 Nouveau badge',label:'Coffre du badge'});
 return list.filter(x=>!cfg.chests.openedKeys[x.key]);
}
function randomContent(){const arr=cfg.chests.content.filter(x=>x.enabled!==false);return arr.length?arr[Math.floor(Math.random()*arr.length)]:{emoji:'🎁',label:'Surprise !',type:'reward'}}
window.openChestHub=function(){if(!cfg.chests.enabled)return;const pending=eligible(),hist=[...cfg.chests.history].reverse().slice(0,10);const o=document.createElement('div');o.className='overlay open';o.innerHTML=`<div class="modal childToolModal"><button class="historyClose" onclick="this.closest('.overlay').remove()">✕</button><h2>🎁 Mes coffres</h2><p>${pending.length?`Tu as ${pending.length} coffre${pending.length>1?'s':''} à ouvrir !`:'Pas de nouveau coffre pour le moment.'}</p><div class="chestGrid">${pending.map(x=>`<button class="chestCard" onclick="openSurpriseChest('${x.key}','${x.label.replace(/'/g,"&#39;")}','${x.reason.replace(/'/g,"&#39;")}')"><span>🎁</span><b>${x.label}</b><small>${x.reason}</small></button>`).join('')}</div>${hist.length?`<h3>Mes derniers coffres</h3><div class="chestHistory">${hist.map(h=>`<div>${h.emoji} <b>${h.label}</b><small>${new Date(h.openedAt).toLocaleDateString('fr-FR')}</small></div>`).join('')}</div>`:''}</div>`;document.body.appendChild(o)};
window.openSurpriseChest=function(k,label,reason){if(cfg.chests.openedKeys[k])return;const gift=randomContent();cfg.chests.openedKeys[k]=new Date().toISOString();cfg.chests.history.push({key:k,label:gift.label,emoji:gift.emoji,type:gift.type,reason,openedAt:new Date().toISOString()});save();document.querySelector('.childToolModal')?.closest('.overlay')?.remove();const o=document.createElement('div');o.className='overlay open';o.innerHTML=`<div class="modal"><div style="font-size:90px;animation:chestPop .6s ease">🎁</div><h2>✨ COFFRE OUVERT ✨</h2><div style="font-size:70px">${gift.emoji}</div><h1>${gift.label}</h1><p>${reason}</p><button class="btn" onclick="this.closest('.overlay').remove();render()">Trop bien ! 🎉</button></div>`;document.body.appendChild(o)};
function contentRows(){return cfg.chests.content.map(x=>`<label class="toggleRow"><span>${x.emoji} ${x.label}</span><input type="checkbox" ${x.enabled!==false?'checked':''} onchange="cfg.chests.content.find(i=>i.id==='${x.id}').enabled=this.checked;save()"></label>`).join('')}
function settings(){return `<div class="settingsGroup chestSettings"><h3>🎁 Coffres surprises</h3><label class="toggleRow"><span>Activer les coffres</span><input type="checkbox" ${cfg.chests.enabled?'checked':''} onchange="cfg.chests.enabled=this.checked;save();render()"></label><label class="toggleRow"><span>Afficher « Mes coffres » à l'enfant</span><input type="checkbox" ${cfg.chests.showChildButton?'checked':''} onchange="cfg.chests.showChildButton=this.checked;save();render()"></label><h4>Quand gagner un coffre ?</h4><label class="toggleRow"><span>🏆 Après une semaine avec au moins 5 jours clôturés</span><input type="checkbox" ${cfg.chests.triggers.weekly?'checked':''} onchange="cfg.chests.triggers.weekly=this.checked;save()"></label><label class="toggleRow"><span>⭐ Quand l'objectif d'étoiles est atteint</span><input type="checkbox" ${cfg.chests.triggers.stars?'checked':''} onchange="cfg.chests.triggers.stars=this.checked;save()"></label><div class="settingInline"><span>Objectif étoiles pour le coffre</span><select onchange="cfg.chests.starsGoal=Number(this.value);save()">${[40,60,80,100,120,150,200,250,300].map(n=>`<option value="${n}" ${Number(cfg.chests.starsGoal)===n?'selected':''}>${n} ⭐</option>`).join('')}</select></div><label class="toggleRow"><span>🏅 Lorsqu'un badge est obtenu</span><input type="checkbox" ${cfg.chests.triggers.badge?'checked':''} onchange="cfg.chests.triggers.badge=this.checked;save()"></label><label class="toggleRow"><span>🎯 Lorsqu'un défi hebdomadaire est réussi</span><input type="checkbox" ${cfg.chests.triggers.challenge?'checked':''} onchange="cfg.chests.triggers.challenge=this.checked;save()"></label><h4>Contenu possible des coffres</h4>${contentRows()}<button class="btn" onclick="previewChest()">👀 Tester un coffre</button></div>`}
window.previewChest=function(){const gift=randomContent(),o=document.createElement('div');o.className='overlay open';o.innerHTML=`<div class="modal"><div style="font-size:90px">🎁</div><h2>Aperçu du coffre</h2><div style="font-size:65px">${gift.emoji}</div><h1>${gift.label}</h1><button class="btn" onclick="this.closest('.overlay').remove()">Fermer</button></div>`;document.body.appendChild(o)};
function inject(){const box=document.querySelector('#settingsView > .box');if(!box)return;box.querySelector('.chestSettings')?.remove();const h=document.createElement('div');h.innerHTML=settings();const n=h.firstElementChild;n.classList.add('settingsCollapsed');const title=n.querySelector('h3');title.classList.add('settingsAccordionTitle');title.insertAdjacentHTML('beforeend','<span class="settingsChevron">⌄</span>');title.onclick=()=>n.classList.toggle('settingsCollapsed');box.appendChild(n)}
function button(){let b=document.getElementById('childChestBtn');if(!b){b=document.createElement('button');b.id='childChestBtn';b.className='childToolBtn chest';b.innerHTML='🎁 Mes coffres';b.onclick=openChestHub;document.getElementById('childSideTools')?.appendChild(b)}const n=eligible().length;b.style.display=cfg.kidMode&&cfg.chests.enabled&&cfg.chests.showChildButton?'':'none';b.innerHTML=`🎁 Mes coffres${n?` (${n})`:''}`}
const prevSettings=window.renderSettings;window.renderSettings=function(){prevSettings();ensure(cfg);inject()};const prevRender=window.render;window.render=function(){prevRender();ensure(cfg);button()};inject();button();
})();